### ISSUE TITLE
Enhancement: ability to trim empty strings

### ISSUE THREAD

**Issue by jreichenberg** [mckamey/jsonml#7]
We're using jsonml dom to serialize a browser dom as jsonml. We have no need to do the reverse trip (jsonml to dom), and therefore want to trim the empty text nodes to make the jsonml much more readable.  A simple change will do it, see: https://github.com/GeneralElectric/jsonml/commit/c32508860d9463882592f303854d06881046491c

Not sure whether / how this fits with the project goals, or how to make this configurable...but FYI.

**Comment by mckamey** [comment]
A few issues that I foresee are 1) [String.trim()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim#Browser_compatibility) isn't universal (but a polyfill / helper method would easily solve that) and 2) a whitespace node isn't necessarily an empty text node.

2) is particularly true in markup. Take for example whitespace between two tags:

  ['p',
    ['strong', 'This sentence has a strong start'],
    ' ',
    ['em', 'but finishes differently.']
  ]

That "empty text node" as you've defined it is important.

That being said, there is logic in the builder script somewhere (it's been years since I've looked through it) which seemed to work well at determining which whitespace nodes could be dropped. The logic was something if a text node only contains whitespace (detection is similar to your code) and is the first or last  child of its parent. That seemed to catch all of the CR/LF (which is what I'm assuming you are targeting) but left the significant whitespace.

I vaguely recall that it also somewhere in there it normalizes sequences of two or more whitespace chars as a single space (since HTML does this when displaying anyway), unless it is inside a PRE block. Maybe I'm misremembering that though as it doesn't take into account CSS mimicking a PRE tag.
